version: '3.9'
services:
  api:
    build: .
    container_name: personal_blog_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=PersonalBlogDb;User Id=namlv;Password=sa;TrustServerCertificate=True;
