name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"   # bất kỳ khi nào tạo tag mới (ví dụ v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./PersonalBlog.API/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/personal-blog:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/personal-blog:${{ github.ref_name }}
